# Generated by Django 4.2.7 on 2023-12-30 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criação", models.DateTimeField(auto_now_add=True)),
                ("atualização", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                ("nome", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "categoria",
                "verbose_name_plural": "categorias",
            },
        ),
        migrations.CreateModel(
            name="Serviço",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criação", models.DateTimeField(auto_now_add=True)),
                ("atualização", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                ("nome", models.CharField(max_length=255)),
                ("custo", models.FloatField()),
                ("descrição", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "serviço",
                "verbose_name_plural": "serviços",
            },
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criação", models.DateTimeField(auto_now_add=True)),
                ("atualização", models.DateTimeField(auto_now=True)),
                ("ativo", models.BooleanField(default=True)),
                ("nome", models.CharField(max_length=255)),
                ("orçamento", models.FloatField()),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projetos",
                        to="projetos.categoria",
                    ),
                ),
                (
                    "serviço",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projetos",
                        to="projetos.serviço",
                    ),
                ),
            ],
            options={
                "verbose_name": "projeto",
                "verbose_name_plural": "projetos",
            },
        ),
    ]
