# Generated by Django 4.2.7 on 2024-01-05 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projetos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projeto",
            name="serviço",
        ),
        migrations.AddField(
            model_name="serviço",
            name="projeto",
            field=models.ForeignKey(
                blank=True,
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="serviços",
                to="projetos.projeto",
            ),
        ),
    ]
